import type { Metadata } from 'next';

import '@/app/globals.css';

export const metadata: Metadata = {
	title: 'The Sync',
	description: 'Generated by create next app',
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
};

export default RootLayout;
