name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create TheSync Frontend Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 🎉 Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: TheSync Frontend - v${{ steps.get_tag.outputs.tag }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
